# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        dependencies = [('auth', '0001_initial')],
    ]

    operations = [
        migrations.CreateModel(
            name='YubicoKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=12)),
                ('client_id', models.IntegerField()),
                ('secret_key', models.CharField(blank=True, max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yubico YubiKey',
                'verbose_name_plural': 'Yubico YubiKeys',
            },
        ),
    ]
